//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEdit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebEdit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Commands]
        ///; Syntax: &lt;Item name&gt;=&lt;Left text&gt;|&lt;Right text&gt;
        ///; Known escape sequences: \\ \t \n \r
        ///&amp;A=&lt;a href=&quot;#&quot;&gt;|&lt;/a&gt;
        ///Div &amp;Class=&lt;div class=&quot;&quot;&gt;|&lt;/div&gt;
        ///Div &amp;Id=&lt;div id=&quot;&quot;&gt;|&lt;/div&gt;
        ///&amp;Em=&lt;em&gt;|&lt;/em&gt;
        ///H&amp;1=&lt;h1&gt;|&lt;/h1&gt;
        ///H&amp;2=&lt;h2&gt;|&lt;/h2&gt;
        ///H&amp;3=&lt;h3&gt;|&lt;/h3&gt;
        ///H&amp;4=&lt;h4&gt;|&lt;/h4&gt;
        ///H&amp;5=&lt;h5&gt;|&lt;/h5&gt;
        ///H&amp;6=&lt;h6&gt;|&lt;/h6&gt;
        ///&amp;Li=&lt;li&gt;|&lt;/li&gt;
        ///&amp;Ol=&lt;ol&gt;|&lt;/ol&gt;
        ///&amp;P=&lt;p&gt;|&lt;/p&gt;
        ///Spa&amp;n=&lt;span&gt;|&lt;/span&gt;
        ///&amp;Strong=&lt;strong&gt;|&lt;/strong&gt;
        ///St&amp;yle=&lt;style&gt;|&lt;/style&gt;
        ///&amp;Table=&lt;table&gt;|&lt;/table&gt;
        ///T&amp;d=&lt;td&gt;|&lt;/td&gt;
        ///T&amp;r=&lt;tr&gt;|&lt;/tr&gt;
        ///&amp;Ul=&lt;ul&gt;|&lt;/ul&gt;
        ///
        ///; Free accelerators: b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebEditIni {
            get {
                return ResourceManager.GetString("WebEditIni", resourceCulture);
            }
        }
    }
}
