name: Native AOT Build
on:
  push:
  pull_request:
    branches:
      - master

permissions:
  contents: read

env:
  PLUGIN_NAME: 'WebEdit'

jobs:
  xds:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build ${{ env.PLUGIN_NAME }}.win32
        run: |
          if ( $(Get-FileHash -A SHA512 .\xds-260-win32.zip).Hash -ne $(Get-Content .\xds-260-win32.zip.sha512) ) { exit 1 }
          $env:PATH += ";${pwd}\xds\bin"
          7z x .\xds-260-win32.zip
          cmd /c .\Src\compile.bat
          echo D | xcopy /DIY ${{ github.workspace }}\WebEdit\Resources Config
          echo "RELEASE_VERSION=$((Get-Item ${{ env.PLUGIN_NAME }}.dll).VersionInfo.FileVersion)" >> $env:GITHUB_ENV
        working-directory: Legacy-v2.1

      - name: Upload ${{ env.PLUGIN_NAME }}.${{ env.RELEASE_VERSION }}.win32
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ env.PLUGIN_NAME }}.${{ env.RELEASE_VERSION }}.win32
          path: |
            Legacy-v2.1/${{ env.PLUGIN_NAME }}.dll
            Legacy-v2.1/Config/

  publish_aot:
    needs: xds
    strategy:
      matrix:
        target_runtime: [ x64, arm64 ]
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: 8.0.x

      - name: Build ${{ env.PLUGIN_NAME }}.${{ matrix.target_runtime }}
        run: |
          dotnet restore
          dotnet build -r win-${{ matrix.target_runtime }} -c Release
          dotnet publish -r win-${{ matrix.target_runtime }} -c Release
          echo D | xcopy /DIY .\Resources Config
          echo F | xcopy /DVY .\bin\Release\net8.0-windows\win-${{ matrix.target_runtime }}\native\${{ env.PLUGIN_NAME }}.dll ${{ env.PLUGIN_NAME }}.dll
          echo "RELEASE_VERSION=$((Get-Item ${{ env.PLUGIN_NAME }}.dll).VersionInfo.FileVersion)" >> $env:GITHUB_ENV
        working-directory: WebEdit

      - name: Upload ${{ env.PLUGIN_NAME }}.${{ env.RELEASE_VERSION }}.${{ matrix.target_runtime }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ env.PLUGIN_NAME }}.${{ env.RELEASE_VERSION }}.${{ matrix.target_runtime }}
          path: |
            WebEdit/${{ env.PLUGIN_NAME }}.dll
            WebEdit/Config/
